name: Integration Tests

on: 
    push: 
        branches:
            - dev-github-actions
    pull_request:
        branches:
            - dev-github-actions

jobs:
    build: 
        runs-on: ubuntu-latest
    
        steps:
            # Checkout the code from the repository
            - name: Checkout code
              uses: actions/checkout@v2

            # Set up .NET SDK
            - name: Set up .NET Core
              uses: actions/setup-dotnet@v3
              with: 
                dotnet-version: '8.0.404'
                        
            - name: Build
              run: dotnet build --configuration Release
            
            - name: Run tests
              run: dotnet test --configuration Release --no-restore
              env: 
                ASPNETCORE_ENVIRONMENT: Development

